In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [2]:
frame = pd.read_csv('./course-files/Mcdonalds.csv', usecols=["Item",'Category','Calories','TotalFat','Serving Size'])

In [3]:
frame.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [4]:
frame.dtypes

Category         object
Item             object
Serving Size     object
Calories          int64
TotalFat        float64
dtype: object

In [5]:
frame.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    object
 1   Item          260 non-null    object
 2   Serving Size  260 non-null    object
 3   Calories      260 non-null    int64
 4   TotalFat      260 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 61.7 KB

In [6]:
frame.loc[1,'Serving Size'] = np.NaN

In [7]:
frame.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,NaN,250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [8]:
frame.loc[2,'Calories'] = np.NaN

In [9]:
frame.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,13.0
1,Breakfast,Egg White Delight,NaN,250.0,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),NaN,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,23.0

In [10]:
frame.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    object
 1   Item          260 non-null    object
 2   Serving Size  259 non-null    object
 3   Calories      259 non-null    float64
 4   TotalFat      260 non-null    float64
dtypes: float64(2), object(3)
memory usage: 61.6 KB

In [11]:
#frame['Calories'].astype('int')

In [12]:
frame['Calories'].fillna(value=0,inplace=True)

In [13]:
frame.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,13.0
1,Breakfast,Egg White Delight,NaN,250.0,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),0.0,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,23.0

In [14]:
frame.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    object
 1   Item          260 non-null    object
 2   Serving Size  259 non-null    object
 3   Calories      260 non-null    float64
 4   TotalFat      260 non-null    float64
dtypes: float64(2), object(3)
memory usage: 61.6 KB

In [15]:
frame['Calories'] = frame['Calories'].astype('int')

In [16]:
frame.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,NaN,250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),0,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [17]:
frame.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    object
 1   Item          260 non-null    object
 2   Serving Size  259 non-null    object
 3   Calories      260 non-null    int32
 4   TotalFat      260 non-null    float64
dtypes: float64(1), int32(1), object(3)
memory usage: 60.6 KB

In [18]:
frame['Category'].value_counts()

Coffee & Tea          95
Breakfast             42
Smoothies & Shakes    28
Chicken & Fish        27
Beverages             27
Beef & Pork           15
Snacks & Sides        13
Desserts               7
Salads                 6
Name: Category, dtype: int64

In [19]:
frame['Category'] = frame['Category'].astype('category')

In [20]:
frame.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,NaN,250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),0,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [21]:
frame.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    category
 1   Item          260 non-null    object
 2   Serving Size  259 non-null    object
 3   Calories      260 non-null    int32
 4   TotalFat      260 non-null    float64
dtypes: category(1), float64(1), int32(1), object(2)
memory usage: 44.3 KB

In [22]:
frame['Serving Size'].value_counts()

16 fl oz cup       45
12 fl oz cup       38
22 fl oz cup       20
20 fl oz cup       16
30 fl oz cup        7
                   ..
7.4 oz (211 g)      1
4 oz (114 g)        1
2 oz (56 g)         1
6.8 oz (192 g)      1
14.2 oz (403 g)     1
Name: Serving Size, Length: 106, dtype: int64

In [23]:
frame['Serving Size'] = frame['Serving Size'].astype('category')

In [24]:
frame.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    category
 1   Item          260 non-null    object
 2   Serving Size  259 non-null    category
 3   Calories      260 non-null    int32
 4   TotalFat      260 non-null    float64
dtypes: category(2), float64(1), int32(1), object(1)
memory usage: 38.2 KB

In [26]:
frame['Calories'].rank().head()

0    116.0
1     83.5
2      9.0
3    178.5
4    156.0
Name: Calories, dtype: float64

In [27]:
frame['CaloriesRank'] = frame['Calories'].rank()

In [28]:
frame.head()

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0,116.0
1,Breakfast,Egg White Delight,NaN,250,8.0,83.5
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),0,23.0,9.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0,178.5
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0,156.0

In [29]:
frame.sort_values(by='Calories').head(20)

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
114,Beverages,Diet Coke (Small),16 fl oz cup,0,0.0,9.0
147,Coffee & Tea,Coffee (Large),16 fl oz cup,0,0.0,9.0
146,Coffee & Tea,Coffee (Medium),16 fl oz cup,0,0.0,9.0
145,Coffee & Tea,Coffee (Small),12 fl oz cup,0,0.0,9.0
140,Coffee & Tea,Iced Tea (Child),12 fl oz cup,0,0.0,9.0
139,Coffee & Tea,Iced Tea (Large),30 fl oz cup,0,0.0,9.0
138,Coffee & Tea,Iced Tea (Medium),21 fl oz cup,0,0.0,9.0
137,Coffee & Tea,Iced Tea (Small),16 fl oz cup,0,0.0,9.0
136,Beverages,Dasani Water Bottle,16.9 fl oz,0,0.0,9.0
124,Beverages,Diet Dr Pepper (Large),30 fl oz cup,0,0.0,9.0
125,Beverages,Diet Dr Pepper (Child),12 fl oz cup,0,0.0,9.0
122,Beverages,Diet Dr Pepper (Small),16 fl oz cup,0,0.0,9.0
117,Beverages,Diet Coke (Child),12 fl oz cup,0,0.0,9.0
116,Beverages,Diet Coke (Large),30 fl oz cup,0,0.0,9.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),0,23.0,9.0
115,Beverages,Diet Coke (Medium),21 fl oz cup,0,0.0,9.0
123,Beverages,Diet Dr Pepper (Medium),21 fl oz cup,0,0.0,9.0
101,Snacks & Sides,Apple Slices,1.2 oz (34 g),15,0.0,18.0
100,Snacks & Sides,Side Salad,3.1 oz (87 g),20,0.0,19.0
106,Desserts,Kids Ice Cream Cone,1 oz (29 g),45,1.5,20.0

In [30]:
frame['CaloriesRank'] = frame['Calories'].rank(ascending=False)

In [31]:
frame.sort_values(by='Calories',ascending=False).head(20)

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,118.0,1.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150,60.0,2.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090,56.0,3.0
34,Breakfast,Big Breakfast with Hotcakes and Egg Whites (La...,15.4 oz (437 g),1050,50.0,4.0
33,Breakfast,Big Breakfast with Hotcakes and Egg Whites (Re...,14.9 oz (423 g),990,46.0,5.0
81,Chicken & Fish,Chicken McNuggets (20 piece),11.4 oz (323 g),940,59.0,6.0
253,Smoothies & Shakes,McFlurry with M&M’s Candies (Medium),16.2 oz (460 g),930,33.0,7.0
246,Smoothies & Shakes,Strawberry Shake (Large),22 fl oz cup,850,24.0,8.5
249,Smoothies & Shakes,Chocolate Shake (Large),22 fl oz cup,850,23.0,8.5
251,Smoothies & Shakes,Shamrock Shake (Large),22 fl oz cup,820,23.0,10.5
243,Smoothies & Shakes,Vanilla Shake (Large),22 fl oz cup,820,23.0,10.5
258,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Medium),14.2 oz (403 g),810,32.0,12.0
28,Breakfast,Big Breakfast (Large Biscuit),10 oz (283 g),800,52.0,13.0
231,Coffee & Tea,Frappé Chocolate Chip (Large),22 fl oz cup,760,31.0,14.0
47,Beef & Pork,Double Quarter Pounder with Cheese,10 oz (283 g),750,43.0,15.5
63,Chicken & Fish,Bacon Clubhouse Crispy Chicken Sandwich,10 oz (284 g),750,38.0,15.5
27,Breakfast,Big Breakfast (Regular Biscuit),9.5 oz (269 g),740,48.0,17.0
51,Beef & Pork,Bacon Clubhouse Burger,9.5 oz (270 g),720,40.0,18.0
248,Smoothies & Shakes,Chocolate Shake (Medium),16 fl oz cup,700,20.0,19.0
245,Smoothies & Shakes,Strawberry Shake (Medium),16 fl oz cup,690,20.0,21.0

In [32]:
frame.sort_values(by='Calories', ascending=False,inplace=True)

In [33]:
frame.head(3)

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,118.0,1.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150,60.0,2.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090,56.0,3.0

In [34]:
frame.nlargest(n=3,columns='Calories')

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,118.0,1.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150,60.0,2.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090,56.0,3.0

In [35]:
frame.nsmallest(n=3,columns='Calories')

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),0,23.0,252.0
147,Coffee & Tea,Coffee (Large),16 fl oz cup,0,0.0,252.0
140,Coffee & Tea,Iced Tea (Child),12 fl oz cup,0,0.0,252.0

In [37]:
np.diag